# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            How to Git - Write the Docs Portland
tagline:          'Welcome to our class'
description:      'An introductory project where attendees get to contribute to a class directory'
url:              https://githubschool.github.io/wtd-hello/
baseurl:          /wtd-hello/

author:
  name:           'beardofedu'
  url:            https://twitter.com/beardofedu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/githubschool/wtd-hello
